apiVersion: v1
clusters:
  - cluster:
      insecure-skip-tls-verify: false
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJQlltbDJMb3NrcnN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNU1EVXlNVFExTVRaYUZ3MHpOVEE1TURNeU1UVXdNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURTWWxkZWkzVnhNSk5rczJYc3NvdkNZSERqd1hxSU9hb3JnNXFYRXNmYkFqZy9VdytUS2JQY0hVdEUKSFhsZlNpK2xjYzZPRVhlYTUrU01rOTJjdW5ZYXQrd21QMzhXQjhsQlVFWG1MY0o4T3NTeWYrWk1lMTNuNS9GQQpYMnJwaEY3dXhuamowRzdPQjBZQ0pEWklRbnhqbGRnWlVWbE5GTzc4L1NiNm43U1ZEZm5qQXNvQlZ5ZnpFM3Q1Ck5CeGpZUjFYbzkxdCtnSW03VXR5Sm1peFUxTDBMcW40alNaTFZMekNZTiszU0NKem9GZTNFN3F3SFVGSjgwcEEKNTBWNjVJR24xcDIxb3lybGl2cXZNbTdxNys3WlJSdTVqV0hZUFp3Y0NDcnlLWUtFT3RxdVczMm01bG1BZEJXZQpGNjJxSGk4d2I2TjdrMXk3SEhHcGcyMXR4bmZsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUTHI0b2pLRWFHUUwyRHl2YU9aSGNwU0xjV0pUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkpLeHFqRjlaNQpURXdQQ0tZRUFQUG9QalNoZmg3c2JqZGZpYzAyMUg2Qk1KYlZsY0U3Z0srT0xDeklTWTJpWTNlTEFvdWRNb2VQClpIWndkMlBJanVUaW1zUUxlTWVIc0o3cW5kVUJsY2JjZENXS0U0ZDljMWtneXFLeGlhbTliRTlqSnpnbXk0eDYKenI1RjhSRVAzVUZ4VXYxSmVSanlHcWQveVlyenFvNmRaMTNYeFEwYWtxb04wbWdYUnAwdFBaV003Y01OK0s3cAp0Q3B4YlQvM1pGSmErMEdHYzNkNDBTaTJlSUJzdTJyQ0daZ3BPdm03ZEZhT0VJeTFBQVp1Z2paaWVFM3FpUWZMCnVJWjBqV2VlRFMyZ1FETjBBdWpscUxUbndoTUgxWFU2MEtNRkZqZTZKc1pBb3ZOTTd1Q0htSHE1ZFR4SjN0ZTMKV3ZlZThRQzR5cm1kCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://hcp-924f2d12-a53b-40c4-91bd-13ac420bea6e.spot.rackspace.com/
    name: sundai-gap-fill
contexts:
  - context:
      cluster: sundai-gap-fill
      namespace: default
      user: ngpc-user
    name: sonnenreich-sundai-gap-fill
  - context:
      cluster: sundai-gap-fill
      namespace: default
      user: oidc
    name: sonnenreich-sundai-gap-fill-oidc
current-context: sonnenreich-sundai-gap-fill
kind: Config
preferences: {}
users:
  - name: ngpc-user
    user:
      token: >-
        eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkNYQ25nd1NFS0JWQl9DbWxvalo0eCJ9.eyJncm91cCI6ImNsb3Vkc3BhY2UtYWRtaW4iLCJuaWNrbmFtZSI6ImphenptaW5kIiwibmFtZSI6IldlcyBTb25uZW5yZWljaCIsInBpY3R1cmUiOiJodHRwczovL2F2YXRhcnMuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3UvNTM0NzQxMz92PTQiLCJ1cGRhdGVkX2F0IjoiMjAyNS0wOS0wN1QxNjoyNToyNC4zOTlaIiwiZW1haWwiOiJ3ZXNAc29ubmVucmVpY2guY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImlzcyI6Imh0dHBzOi8vbG9naW4uc3BvdC5yYWNrc3BhY2UuY29tLyIsImF1ZCI6Im13RzNsVU1WOEt5ZU1xSGU0Zko1QmIzbk0xdkJ2Uk5hIiwic3ViIjoiZ2l0aHVifDUzNDc0MTMiLCJpYXQiOjE3NTcyNjIzMjksImV4cCI6MTc1NzUyMTUyOSwic2lkIjoiWG9rNmx0Qnpiekw2N0xwcUJ0WGc3ejY3VENBU0pGaWciLCJub25jZSI6ImFEWjVUMWs0Y0ZJMlVFTTBZWEUzWVROVFVFTndPVWx4TFVrNGRGVlRTMjgyWmpCQ2VVWTFSblF1TWc9PSIsIm9yZ19pZCI6Im9yZ19MQmFlTkhjQnZHeGxrSmdqIn0.K4MX2b6RinjMYqJPN2qb2q6np5Z9NxkOU3RhmeE49S8wFNCtadRFpRvVfxJ4iq-AeqdNrt5CjSiCerdckCT1FNfJjC-fqDeKhIdWcCExgDPcu3R89c3t0ANVdm_wrcaKaUE7wOlNpRP0CjUhNCrNo_6baqyhD6XSwaI_oGn04MS3nl8ioXoAS6QeyY7I67-3bklnYvdt8uNW6kXJHdURSEpuBveMzMeLNKGpFkMCVTz_pt-LaSAWFfYcbRkZ0CUWy84UEGnJZIQtqMpw-MA4YNjvrCZ-tVm7_DpzgPFterf6NyebPW-YDAj94IMTbVu2ONyZ2Hl4HAkBbZ-u_qNSvw
  - name: oidc
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - '--oidc-issuer-url=https://login.spot.rackspace.com/'
          - '--oidc-client-id=mwG3lUMV8KyeMqHe4fJ5Bb3nM1vBvRNa'
          - '--oidc-extra-scope=openid'
          - '--oidc-extra-scope=profile'
          - '--oidc-extra-scope=email'
          - '--oidc-auth-request-extra-params=organization=org_LBaeNHcBvGxlkJgj'
          - '--token-cache-dir=~/.kube/cache/oidc-login/org_LBaeNHcBvGxlkJgj'
        command: kubectl
        env: null
        interactiveMode: IfAvailable
        provideClusterInfo: false
